### ISSUE TITLE
How to create a persistent actor

### ISSUE THREAD

**Issue by Tochemey** [hedisam/goactor#1]
Hello, I would like to know how to spawn a persistent actor.

By the way nice job.

**Comment by Tochemey** [comment]
No need to reply.

**Comment by hedisam** [comment]
Hey @Tochemey 
Thanks for your interest in this project and sorry for my late response, I was on holiday.

I'm not sure what you mean by a persistent actor, but if what you want is an actor which restores its state after it restarts then I'm afraid the current implementation doesn't support such feature and also afaik this should be against the Actor model philosophy since the state could get corrupted and be the actual root of panic/malfunctioning that's why we always spawn a fresh actor to avoid such things. But you can always store your actor's state in a DB/Filesystem or any persistent storage you prefer.
